package panel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;

public class TimeBar extends JComponent {

    private JPanel panel1;
    private JLabel TimeLabel;
    private UIController uiController;

    private Timer timer;
    public TimeBar() {
        uiController = UIController.UIControllerinstance();
        uiController.addTimerBar(this);

    }

    public void setTimer(long time) {
        SimpleDateFormat df = new SimpleDateFormat("mm:ss");
        TimeLabel.setText(df.format(time * 1000));
    }

    public void startTimer() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setTimer(uiController.getTime());
            }
        });

        timer.setInitialDelay(10);
        timer.start();
    }


    public void stopTimer() {
        timer.stop();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        TimeLabel = new JLabel();
        TimeLabel.setText("Time");
        panel1.add(TimeLabel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
